# Generated by Django 2.2 on 2022-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('team_name', models.CharField(blank=True, max_length=500, null=True)),
                ('team_first_color', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
