# Generated by Django 2.2 on 2022-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220414_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_id',
            field=models.IntegerField(blank=True),
        ),
    ]
