# Generated by Django 2.2 on 2022-04-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20220414_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_id',
            field=models.IntegerField(blank=True),
        ),
    ]
