# Generated by Django 2.2 on 2022-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20220415_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='country_id',
            field=models.IntegerField(blank=True),
        ),
    ]
