# Generated by Django 2.2 on 2022-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='minutes_played',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_possession_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='xg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
