# Generated by Django 2.2 on 2022-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20220415_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='match_id',
            field=models.IntegerField(blank=True),
        ),
    ]
