# Generated by Django 2.2 on 2022-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('match_home_team_id', models.IntegerField(blank=True, null=True)),
                ('match_away_team_id', models.IntegerField(blank=True, null=True)),
                ('match_home_score', models.IntegerField(blank=True, null=True)),
                ('match_away_score', models.IntegerField(blank=True, null=True)),
                ('match_home_penalty_score', models.IntegerField(blank=True, null=True)),
                ('match_away_penalty_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
