# Generated by Django 2.2 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
